languages: [en, ru, fr, de, tr, ko, zh]
langNames:
  en: English
  ru: Русский
  fr: Français
  de: Deutsch
  tr: Türkçe
  ko: 한국어
  zh: 中文

lang:
  en:
    # header
    title: BANK - Bitcoin Wallet
    slogan: Control your money!
    # slider
    balance: Easy to use
    balance_desc: Every currencies balances is at hand. Send money in two clicks. Easy adress sharing
    transactions: Transactions History
    transactions_desc: Transaction history in one list. Quick view of full information from customizable resources
    settings: Personalization
    settings_desc: Set the appearance of the application for yourself, configure data resources, select the language, light or dark mode
  ru:
    title: BANK - Биткоин Кошелек
    slogan: Контролируй свои деньги!
    # slider
    balance: Easy to use
    balance_desc: Every currencies balances is at hand. Send money in two clicks. Easy adress sharing
    transactions: Transactions History
    transactions_desc: Transaction history in one list. Quick view of full information from customizable resources
    settings: Personalization
    settings_desc: Set the appearance of the application for yourself, configure data resources, select the language, light or dark mode
  fr:
    # header
    title:  BANK - Portefeuille Bitcoin
    slogan: Contrôler votre argent!
    # slider
    balance: Easy to use
    balance_desc: Every currencies balances is at hand. Send money in two clicks. Easy adress sharing
    transactions: Transactions History
    transactions_desc: Transaction history in one list. Quick view of full information from customizable resources
    settings: Personalization
    settings_desc: Set the appearance of the application for yourself, configure data resources, select the language, light or dark mode
  de:
    # header
    title: BANK - Bitcoin Wallet
    slogan: Kontrolliere dein Geld!
    # slider
    balance: Easy to use
    balance_desc: Every currencies balances is at hand. Send money in two clicks. Easy adress sharing
    transactions: Transactions History
    transactions_desc: Transaction history in one list. Quick view of full information from customizable resources
    settings: Personalization
    settings_desc: Set the appearance of the application for yourself, configure data resources, select the language, light or dark mode
  tr:
    # header
    title: BANK - Bitcoin Cüzdanı!
    slogan: Paranızı Kontrol Edin!
    # slider
    balance: Easy to use
    balance_desc: Every currencies balances is at hand. Send money in two clicks. Easy adress sharing
    transactions: Transactions History
    transactions_desc: Transaction history in one list. Quick view of full information from customizable resources
    settings: Personalization
    settings_desc: Set the appearance of the application for yourself, configure data resources, select the language, light or dark mode
  ko:
    # header
    title: BANK - 비트 동전 지갑
    slogan: 당신의 돈을 지켜라!
    # slider
    balance: Easy to use
    balance_desc: Every currencies balances is at hand. Send money in two clicks. Easy adress sharing
    transactions: Transactions History
    transactions_desc: Transaction history in one list. Quick view of full information from customizable resources
    settings: Personalization
    settings_desc: Set the appearance of the application for yourself, configure data resources, select the language, light or dark mode
  zh:
    # header
    title: BANK - 比特币钱包
    slogan: 掌控自己的钱财!
    # slider
    balance: Easy to use
    balance_desc: Every currencies balances is at hand. Send money in two clicks. Easy adress sharing
    transactions: Transactions History
    transactions_desc: Transaction history in one list. Quick view of full information from customizable resources
    settings: Personalization
    settings_desc: Set the appearance of the application for yourself, configure data resources, select the language, light or dark mode
